name: My first Github Action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world!!"
      - run: echo "hello-world2!!"
  print-hello-world2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "again hello-world!!"
      - run: echo "again hello-world2!!"
